{
  config,
  pkgs,
  ...
}: let
  configPaths = [
    {
      name = "glow";
      path = "${config.home.homeDirectory}/.config/nixcfg/glow";
    }
    {
      name = "wlppr";
      path = "${config.home.homeDirectory}/.config/nixcfg/wlppr";
    }
    {
      name = "scripts";
      path = "${config.home.homeDirectory}/.config/nixcfg/scripts";
    }
    {
      name = "btop";
      path = "${config.home.homeDirectory}/.config/nixcfg/btop";
    }
  ];
in {
  xdg.configFile = builtins.listToAttrs (map (c: {
      name = c.name;
      value = {
        source = config.lib.file.mkOutOfStoreSymlink c.path;
      };
    })
    configPaths);

  xresources.properties = {
    "Xcursor.size" = 24;
    "Xft.dpi" = 96;
  };

  dconf = {
    enable = true;
    settings."org/gnome/desktop/interface".color-scheme = "prefer-dark";
  };

  wayland = {
    windowManager = {
      hyprland = {
        enable = true;
        package = pkgs.hyprland;
        xwayland = {
          enable = true;
        };
        settings = {
          autogenerated = 0;

          "$terminal" = "ghostty";
          "$fileManager" = "nautilus";
          "$menu" = "wofi --show drun";
          "$LAPTOP_KB_ENABLED" = true;

          monitor = [
            "eDP-1,1920x1080,auto,1"
            ",preferred,auto,1"
          ];

          device = {
            name = "at-translated-set-2-keyboard";
            enabled = "$LAPTOP_KB_ENABLED";
          };

          exec-once = [
            "pkill -f waybar && waybar &"
            "waypaper --restore &"
            "kanshi &"
          ];

          env = [
            "XCURSOR_SIZE,24"
            "XCURSOR_THEME,WhiteSur-cursors"
            "HYPRCURSOR_SIZE,24"
          ];

          general = {
            gaps_in = 2;
            gaps_out = 4;

            border_size = 1;

            "col.active_border" = "rgba(5e5e5ecc)";
            "col.inactive_border" = "rgba(3a3a3a99)";

            resize_on_border = true;
            allow_tearing = false;
            layout = "dwindle";
          };

          decoration = {
            rounding = 8;
            active_opacity = 1.0;
            inactive_opacity = 1.0;

            shadow = {
              enabled = true;
              range = 9;
              render_power = 2;
              color = "rgba(00000055)";
            };

            blur = {
              enabled = false;
              # size = 1
              # passes = 1
              vibrancy = 0.0;
            };
          };

          animations = {
            enabled = true;

            bezier = [
              "superSmoothIn, 0.9, 0, 0.1, 1"
              "superSmoothOut, 0.1, 0, 0.9, 1"
              "superSmoothInOut, 0.95, 0, 0.05, 1"
            ];

            animation = [
              # Global
              "global, 1, 3.5, superSmoothInOut"

              # Windows
              "windows, 1, 0.5, superSmoothInOut"
              "windowsIn, 1, 0.6, superSmoothIn, slide"
              "windowsOut, 1, 0.6, superSmoothOut, slide"

              # Workspaces
              "workspaces, 1, 1.0, superSmoothInOut, slide"

              # Fade animations
              "fadeIn, 1, 0.3, superSmoothIn"
              "fadeOut, 1, 0.3, superSmoothOut"

              # Layers animations
              "layers, 1, 0.6, superSmoothInOut"
              "layersIn, 1, 0.6, superSmoothIn, slide"
              "layersOut, 1, 0.6, superSmoothOut, slide"

              # Specific fade animations for layers
              "fadeLayersIn, 1, 0.4, superSmoothIn"
              "fadeLayersOut, 1, 0.4, superSmoothOut"
            ];
          };

          dwindle = {
            pseudotile = true; # master switch for pseudotile. enable with mainMod + P
            preserve_split = true;
          };

          master = {
            new_status = "master";
          };

          misc = {
            force_default_wallpaper = 0;
            disable_hyprland_logo = true;
            vfr = true;
          };

          input = {
            kb_layout = "us";
            kb_variant = "";
            kb_model = "";
            kb_options = "";
            kb_rules = "";

            follow_mouse = 1;
            sensitivity = 0; # -1.0 to 1.0, 0 means no modifications

            touchpad = {
              natural_scroll = false;
            };
          };

          gestures = {
            workspace_swipe = true;
          };

          "$mainMod" = "SUPER";

          bind = [
            "$mainMod, Q, exec, $terminal"
            "$mainMod, C, killactive, "
            "$mainMod, M, exit, "
            "$mainMod, E, exec, $fileManager"
            "$mainMod, V, togglefloating, "
            "$mainMod, R, exec, $menu"
            "$mainMod, P, pseudo, " # dwindle
            "$mainMod, J, togglesplit" # dwindle

            "SUPER_SHIFT, R, exec, hyprctl reload"
            ", Print, exec, grimblast --notify copy area"

            "$mainMod, left, movefocus, l"
            "$mainMod, right, movefocus, r"
            "$mainMod, up, movefocus, u"
            "$mainMod, down, movefocus, d"

            "$mainMod, 1, workspace, 1"
            "$mainMod, 2, workspace, 2"
            "$mainMod, 3, workspace, 3"
            "$mainMod, 4, workspace, 4"
            "$mainMod, 5, workspace, 5"
            "$mainMod, 6, workspace, 6"
            "$mainMod, 7, workspace, 7"
            "$mainMod, 8, workspace, 8"
            "$mainMod, 9, workspace, 9"
            "$mainMod, 0, workspace, 10"

            "$mainMod SHIFT, 1, movetoworkspace, 1"
            "$mainMod SHIFT, 2, movetoworkspace, 2"
            "$mainMod SHIFT, 3, movetoworkspace, 3"
            "$mainMod SHIFT, 4, movetoworkspace, 4"
            "$mainMod SHIFT, 5, movetoworkspace, 5"
            "$mainMod SHIFT, 6, movetoworkspace, 6"
            "$mainMod SHIFT, 7, movetoworkspace, 7"
            "$mainMod SHIFT, 8, movetoworkspace, 8"
            "$mainMod SHIFT, 9, movetoworkspace, 9"
            "$mainMod SHIFT, 0, movetoworkspace, 10"

            "$mainMod, S, togglespecialworkspace, magic"
            "$mainMod SHIFT, S, movetoworkspace, special:magic"

            # Scroll through existing workspaces with mod+scroll
            "$mainMod, mouse_down, workspace, e+1"
            "$mainMod, mouse_up, workspace, e-1"
          ];

          bindm = [
            # move/resize window using LMB/RMB and dragging
            "$mainMod, mouse:272, movewindow"
            "$mainMod, mouse:273, resizewindow"
          ];

          bindel = [
            # Laptop multimedia keys for volume and LCD brightness
            ",XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
            ",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
            ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
            ",XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
            ",XF86MonBrightnessUp, exec, brightnessctl s 10%+"
            ",XF86MonBrightnessDown, exec, brightnessctl s 10%-"
          ];

          bindl = [
            # Requires playerctl
            ", XF86AudioNext, exec, playerctl next"
            ", XF86AudioPause, exec, playerctl play-pause"
            ", XF86AudioPlay, exec, playerctl play-pause"
            ", XF86AudioPrev, exec, playerctl previous"
          ];

          # window rule v1
          windowrule = [];

          # window rule v2
          windowrulev2 = [
            "float,class:org\.gnome\.Nautilus"
            "suppressevent maximize, class:.*"
            "float,class:xdg-desktop-portal-gtk,title:.*wants to open"

            # fix some dragging issues with XWayland
            "nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0"
          ];
        };
      };
    };
  };

  services = {
    kanshi = {
      enable = true;
      package = pkgs.kanshi;
      settings = [
        {
          profile = {
            name = "laptop";
            outputs = [
              {
                criteria = "eDP-1";
                status = "enable";
                scale = 1.0;
              }
            ];
          };
        }
        {
          profile = {
            name = "external";
            outputs = [
              {
                criteria = "eDP-1";
                status = "disable";
              }
              {
                criteria = "HDMI-A-1";
                status = "enable";
                mode = "2560x1440@144Hz";
                position = "0,0";
              }
            ];
          };
        }
      ];
    };

    hyprpaper = {
      enable = true;
      package = pkgs.hyprpaper;
      settings = {
        ipc = "on";
        splash = false;
        splash_offset = 2.0;

        preload = [
          "~/.config/nixcfg/wlppr/0.jpg"
        ];

        wallpaper = [
          "eDP-1, ~/.config/nixcfg/wlppr/0.jpg"
          "HDMI-A-1, ~/.config/nixcfg/wlppr/0.jpg"
        ];
      };
    };

    dunst = {
      enable = true;
      package = pkgs.dunst;
      settings = {
        global = {
          monitor = 0;
          follow = "mouse";
          geometry = "200x20-10+10";
          indicate_hidden = "yes";

          background = "#0c0d0c";
          forground = "#c5c5c9";

          font = "0xProto Nerd Font 8";

          enable_recursive_icon_lookup = true;
          icon_position = "left";
          max_icon_size = 48;
          min_icon_size = 24;

          format = "<b>%a</b>\n%s\n%b\n";

          notification_limit = 5;
          timeout = 10;
          sort = "yes";
          stack_duplicates = true;

          mouse_left_click = ["do_action" "close_current"];
          mouse_middle_click = ["close_current"];
          mouse_right_click = ["close_all"];

          layer = "overlay";
          force_wayland = false;

          frame_width = 1;
          frame_color = "#5e5e5e";
          corner_radius = 8;
        };

        urgency_low = {
          background = "#0c0d0c";
          foreground = "#888888";
          timeout = 5;
        };
        urgency_normal = {
          background = "#0c0d0c";
          foreground = "#c5c5c9";
          timeout = 10;
        };
        urgency_critical = {
          background = "#0c0d0c";
          foreground = "#ffffff";
          frame_color = "#ff0000";
          timeout = 0;
        };
      };
    };
  };

  gtk = {
    enable = true;
    theme = {
      name = "Adwaita-dark";
      package = pkgs.gnome-themes-extra;
    };
  };

  qt = {
    enable = true;
    platformTheme = {name = "adwaita";};
    style = {
      name = "adwaita-dark";
      package = pkgs.adwaita-qt;
    };
  };
}
