# Reload tmux config with `Prefix + r`
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Create new windows and panes with intuitive keys
bind t new-window
bind e split-window -v -c "#{pane_current_path}"
bind o split-window -h -c "#{pane_current_path}"

# Navigate through windows
bind h previous-window
bind l next-window

# Detach from current session
bind d detach-client

# Close current tab (window)
bind w kill-window

# toggle fullscreen pane
bind-key z resize-pane -Z

# Swap current window with another window
bind < swap-window -t -1
bind > swap-window -t +1

# Copy mode and clipboard integration
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Renumber windows automatically
set -g renumber-windows on

# Window titles
setw -g automatic-rename on
set-option -g set-titles on
set-option -g set-titles-string "#S / #W"

# Status bar configuration with Gruvbox Dark Hard colors
set -g status-position top
set -g status-justify left
set -g status-style fg=#d5c4a1,bg=default
set -g status-left-length 40
set -g status-left "#[fg=#fabd2f,bg=default] #S "  # Session name
set -g status-right "#[fg=#fabd2f,bg=default]%a %d %b %Y %I:%M %p"  # Date/time
set -g window-status-format "#[fg=#d5c4a1,bg=default]#I:#W"  # Inactive windows
set -g window-status-current-format "#[fg=#1d2021,bg=#83a598,bold] #I:#W "  # Active window
set -g status-interval 1

# Pane borders for a more aesthetic look
set -g pane-border-style fg='#3c3836',bg=#1d2021  # Inactive borders in dark gray
set -g pane-active-border-style fg='#83a598',bg=#1d2021  # Active borders in blue
